### StateVar Definitions
actions = [
    {name = "u", is_ext_input = true, low_value = -15, high_value = 15},
]

observations = [
    {name = "f", is_ext_input = true, low_value = 0, high_value = 100},
    {name = "s", is_ext_output = true, low_value = -15, high_value = 15},
    {name = "v", is_ext_output = true, low_value = -20, high_value = 20},
    {name = "a", is_ext_output = true, low_value = -20.0, high_value = 20.0},
]

### Additional State Parameters
[state_parameters]
max_torque=5
abc=3
